name: Blob storage website CI

on:
  push:
    branches: [ "main" ]
    
env:
  GENERATE_SOURCEMAP: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
   # - name: Upload build
   #   uses: actions/upload-artifact@v3
   #   with:
   #     name: build-dir
   #     path: build
    
  #deploy:

    #runs-on: ubuntu-latest
    
    #needs: build
    #steps:
    #- uses: actions/checkout@v2
    #- name: Get build
    #  uses: actions/download-artifact@v3
    #  with:
    #    name: build-dir
    #    path: build
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            ls
            az storage blob delete-batch --account-name tocawebsite --auth-mode key -s '$web' --pattern 'static'
            az storage blob upload-batch --overwrite true --account-name tocawebsite --auth-mode key -d '$web' -s build
    
    - name: logout
      run: |
            az logout
      if: always()
